{% set name = "torchani" %}
{% set version = "2.2.1" %}
{% set torchani_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/aiqm/{{ name }}.git
  git_rev: v{{ version }}

build:
  number: 0
  skip: true  # [win]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torchani_proc_type }}                                                  # [cuda_compiler_version == "None"]
  string: py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torchani_proc_type }}  # [cuda_compiler_version != "None"]
  script:
    - "{{ PYTHON }} -m pip install . -vvv --no-deps"  # [cuda_compiler_version == "None"]
    - "{{ PYTHON }} -m pip install . --global-option='--ext-all-sms' -vvv --no-deps"  # [cuda_compiler_version != "None"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]

  host:
    - python
    - setuptools_scm
    - cmake
    - ninja
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - numpy >=1.18
    - pytorch-gpu {{ pytorch_version }}  # [cuda_compiler_version != "None"]
    - pytorch-cpu {{ pytorch_version }}  # [cuda_compiler_version != "None"]

  run:
    - python
    - setuptools
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - numpy
    - torchvision >=0.10
    - pytorch
    - pytorch-gpu                            # [cuda_compiler_version != "None"]
    - pytorch-cpu                            # [cuda_compiler_version == "None"]

test:
  imports:
    - torchani
    - torchani.cuaev
  source_files:
    - tests/*
    - download.sh
    - dataset/*
  commands:
    - pip install pytest pynvml pkbar ase parameterized
    - ./download.sh
    # cuaev test
    - python -m pytest -v -s tests/*.py

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
    - yueyericardo
