{% set name = "torchani" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/aiqm/{{ name }}.git
  git_rev: v{{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version not in (undefined, 'None')]

  host:
    - python {{ python }}
    - setuptools_scm
    - cmake
    - ninja
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - defaults::numpy >=1.18
    - pytorch-gpu {{ pytorch_version }}  # [cuda_compiler_version not in (undefined, 'None')]
    - pytorch-cpu {{ pytorch_version }}  # [osx]

  run:
    - python {{ python }}
    - setuptools
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - defaults::numpy >=1.18
    - torchvision >=0.10
    - pytorch
    # ^ needed so conda build does not complain about overlinking
    - {{ pin_compatible('pytorch-gpu', max_pin='x.x.x') }}  # [cuda_compiler_version not in (undefined, 'None')]
    - {{ pin_compatible('pytorch-cpu', max_pin='x.x.x') }}  # [osx]

build:
  number: 0
  skip: true  # [win or (linux and cuda_compiler_version in (undefined, 'None', '10.2'))]
  string: py{{py}}_torch1.9.1_cuda11.1
  script:
    - "{{ PYTHON }} -m pip install . --global-option='--ext-all-sms' -vvv --no-deps"

test:
  imports:
    - torchani
    - torchani.cuaev
  source_files:
    - tests/*
    - download.sh
    - dataset/*
  commands:
    - pip install pytest pynvml pkbar ase parameterized
    - ./download.sh
    # cuaev test
    - python -m pytest -v -s tests/*.py

about:
  home: https://roitberg.chem.ufl.edu
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
    - yueyericardo
