# Notes: this receipt is based on torchvision-feedstock: https://github.com/conda-forge/torchvision-feedstock/blob/master/recipe/meta.yaml

{% set name = "torchani" %}
{% set version = "2.2.1" %}
{% set torchani_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/aiqm/{{ name }}.git
  git_rev: {{ version }}

build:
  number: 0
  skip: true  # [win]
  string: py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torchani_proc_type }}                                                  # [cuda_compiler_version == "None"]
  string: py{{ CONDA_PY }}cuda{{ cuda_compiler_version|replace('.', '') }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}_{{ torchani_proc_type }}  # [cuda_compiler_version != "None"]
  script:
    # cuda 10.2 does not have cub, and need to be manually downloaded
    # - sudo yum install wget unzip -y                                                  # [cuda_compiler_version == '10.2']
    # but the current master version of cub has conflict with cuda 10.2, so cuaev will not support cuda 10.2 for now.
    - "{{ PYTHON }} -m pip install . -vvv --no-deps"                                    # [cuda_compiler_version in ("None", '10.2')]
    - "{{ PYTHON }} -m pip install . --global-option='--cuaev-all-sms' -vvv --no-deps"  # [cuda_compiler_version not in ("None", '10.2')]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
    - sysroot_linux-64 ==2.17                # [linux64]

  host:
    - python
    - pip
    - setuptools_scm
    - importlib_metadata
    - numpy
    - pytorch
    - pytorch-gpu {{ pytorch_version }}  # [cuda_compiler_version != "None"]
    - pytorch-cpu {{ pytorch_version }}  # [cuda_compiler_version == "None"]

  run:
    - python
    - pip
    - importlib_metadata
    - lark-parser
    - requests
    - h5py
    - numpy
    - torchvision >=0.10
    - pytorch
    - pytorch-gpu {{ pytorch_version }}  # [cuda_compiler_version != "None"]
    - pytorch-cpu {{ pytorch_version }}  # [cuda_compiler_version == "None"]

test:
  imports:
    - torchani
    - torchani.cuaev                     # [cuda_compiler_version != "None"]
  source_files:
    - tests/*
    - download.sh
    - dataset/*
  commands:
    - python -m pip install pytest pynvml pkbar ase parameterized expecttest  # [linux64]
    - sudo yum install wget unzip -y                                          # [linux64]
    - ./download.sh                                                           # [linux64]
    # cuaev test
    - cd tests; python -m pytest -v -s test_cuaev.py                          # [linux64]

about:
  home: https://github.com/aiqm/torchani
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Accurate Neural Network Potential on PyTorch'

extra:
  recipe-maintainers:
    - hadim
    - yueyericardo
